spring:
  liquibase:
    contexts: dev
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/malabaakdb}
    username: ${DB_USER:malabaak}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: validate
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
        transport:
          protocol: smtp
    username: ${APP_MAIL_ACCOUNT}
    host: smtp.gmail.com
    password: ${APP_MAIL_PASSWORD}
    port: '587'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 536122725413-vj2dr5q9ebhs4j5q9jljtpq74s30siaa.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
logging:
  level:
    io.joework: DEBUG
    org:
      springframework:
        web: DEBUG
        security: TRACE
        mail: DEBUG
      hibernate:
        sql: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem


app:
  hostname: localhost
  verification:
    baseUrl: "http://${app.hostname}:${server.port}"

server:
  port: 8080

token:
  access-token-config:
    expiry-time-in-seconds: 3600
  refresh-token-config:
    expiry-time-in-seconds: 86400