spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/malabaak}
    username: ${DB_USER:malabaak}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver