spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/malabaakdb}
    username: ${DB_USER:malabaak}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: validate
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
        transport:
          protocol: smtp
    username: ${APP_MAIL_ACCOUNT}
    host: smtp.gmail.com
    #          TODO: remove that before pushing to github
    password: ${APP_MAIL_PASSWORD}
    port: '587'
logging:
  level:
    web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE

## setting the change master file for liquibase
#  liquibase:

#    change-log: classpath:/db/changelog/db.changelog-master.yaml
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem